### ISSUE TITLE
Recipe Name Not Passing to View Substitutes Handlebars Template

### ISSUE THREAD

**Issue by kiserd** [kiserd/OSU-361-Project#10]
When a user navigates to the "View Substitutes" page, the associated recipe name does not populate at the top of the page. The precise steps required in viewing this bug is to navigate to the "Choose Recipe" page, choose a recipe to "view ingredients" for, then click the "view substitutes" for an ingredient.

One can quickly fix this issue by making sure that the recipe name is harbored under the same key in the context dictionary as is specified in the handlebars template.
![image](https://user-images.githubusercontent.com/59572911/100794663-ba7f8480-33d2-11eb-9648-4929e6ce43a7.png)

**Comment by fraszle** [comment]
This has been fixed from the looks of it, thanks Logan!!
