### ISSUE TITLE
Recipe Name Not Passing to View Ingredients Handlebars Template

### ISSUE THREAD

**Issue by kiserd** [kiserd/OSU-361-Project#9]
The recipe name associated with ingredients being viewed is not populating in the "View Ingredients" template. The precise steps to see the bug are to click a "View Ingredients" button from the "Choose Recipe" page. The precise steps to fix this issue are as follows:
1. Determine whether the recipe name is being passed to the handlebars template via context. If it is being passed to the template, check what key in the context dictionary references the recipe name.
2. Determine which key is being used to reference the recipe name on the template side of things. Make sure the key matches that which is being used to pass the value in context.
3. Make sure the keys are the same and confirm the recipe name populates in the app
![image](https://user-images.githubusercontent.com/59572911/100793671-5dcf9a00-33d1-11eb-91c0-704767eb8cd3.png)

**Comment by fraszle** [comment]
This was fixed by Logan, nice work!! :)
